#!/bin/bash

function die { echo -ne '\033[31m'; echo $@; echo -ne '\033[0m'; exit 1; }

# logfile=log/deploy.log
# restart=tmp/restart.txt
# umask 002

git diff --quiet \
    || die "Changes to production files found. Aborting."
[ -z "$( git ls-files --exclude-standard --others )" ] \
    || die "Untracked files in $GIT_WORK_TREE. Aborting."

git checkout -f
